global using Dfe.Testing.Pages.Public;
global using Dfe.Testing.Pages.Public.Commands;
global using Dfe.Testing.Pages.Public.Components.GDS.Button;
global using Dfe.Testing.Pages.Public.Components.GDS.CookieBanner;
global using Dfe.Testing.Pages.Public.Components.Link;
global using Dfe.Testing.Pages.Public.Selector;
global using Dfe.Testing.Pages.Public.WebDriver;
global using FluentAssertions;
global using Microsoft.Extensions.DependencyInjection;
